#####################################
# Coursera: Getting and Cleaning Data
# Course Project: UCI_HAR dataset
# hwang56
# R script
# 07/24/2014
#####################################

#### Tasks on data cleaning ####
# 1. Download the datasets (zipped) from URL
# 2. Merge training and test datasets.
# 3. Extract measurements only on mean and standard deviation (std) for each type of measurements
# 4. Use descriptive activity names (6 activities, activity_labels.txt) to name the activities (1:6 from y dataset)
# 5. Labels dataset with variable names (feature.txt)
# 6. Creates a seperate tidy dataset with the average of values of each variable for each subject and activity.

#### Description on UCI_HAR Dataset
#*** training dataset ***#
# 1. X_train.txt: main data for the training group, 7352 obs. of 561 variables
# 2. y_train.txt: 6 levels (1:6) activities, see activity_labels.txt for labels.
# 3. subject_train.txt: IDs for individuals from the training group.

#*** testing dataset ***#
# 1. X_test.txt: main data for the testing group, 2947 obs. of 561 variables
# 2. y_test.txt: 6 levels (1:6) activities, see activity_labels.txt for labels.
# 3. subject_test.txt: IDs for individuals from the testing group.

#*** files containing additional information ***#
# 1. features.txt: variable names for the 561 variables
# 2. activity_labels.txt: activity labels for 6 types of activities
# 3. feature_info.txt: further detailed information on generating variables (561 length feature vector) from the raw signal measurments 
#    (Inertial Signals)signals
# 4. README.txt: Project title and contact information; Overal description on the project; list of files in the dataset.  


#### Strategy and Steps for data cleaning ####
# 1. Read in dataset
# 2. Data cleaning including: 
	 # 1) To merge the training and testing data sets into one big dataframe X.
     # 2) To name the column names of X with the 561-length feature vector.       
	 # 3) To combine "subject" and "activity_labels" files with X. 
	 # 4) To extract information from the 561-length feature vector that only contains mean and standard deviation 
			 # of the variables for each measurement.
	 # 3) Finally, the first tidy dataset (X_sub1) is generated following the above four steps.
# 3. The second tidy data set (X_sub2) was generated by function aggregate()
     # which the average values of each variable for each subject and activity.

#### Step I. Read in dataset
setwd("C:\\Users\\hang\\Desktop\\Coursera\\Data.Cleaning\\CourseProject\\getdata-projectfiles-UCI HAR Dataset\\UCI HAR Dataset\\")

	# The training group
X_train<-read.table("./train/X_train.txt", sep="")
str(X_train) # 7352 obs. of 561 variables
y_train<-read.table("./train/y_train.txt", sep="") # 7352 obs. of 1 variable
str(y_train)
subject_train<-read.table("./train/subject_train.txt", sep="") # 7352 obs. of 1 variable
str(subject_train)

	# The testing group
X_test<-read.table("./test/X_test.txt", sep="")
str(X_test) # 2947 obs. of 561 variables
y_test<-read.table("./test/y_test.txt", sep="") # 2947 obs. of 1 variable
str(y_test)
subject_test<-read.table("./test/subject_test.txt", sep="") # 2947 obs. of 1 variable
str(subject_test)

	# features, activity_labels
features<-read.table("features.txt", sep="")# 561 obs. of 2 variables, features$V2 the features
activity_labels<-read.table("activity_labels.txt", sep="")

#### Step II. Merge files

sub_y_train<-cbind(subject_train, y_train)
str(sub_y_train)
head(sub_y_train)

sub_y_test<-cbind(subject_test, y_test)
str(sub_y_test)
head(sub_y_test)

sub_y<-rbind(sub_y_train, sub_y_test) 
head(sub_y)
colnames(sub_y)<-c("Subject", "Activity")
levels(suy$Activity)<-activity_labels$V2
dim(sub_y)
head(sub_y)

X_train[1:2, 1:5]
X_test[1:2, 1:5]

X<-rbind(X_train, X_test)
X[1:2, 1:5]
dim(X) 
colnames(X)<-features$V2
dim(X)

grep.mean<-grep("mean", features$V2)
length(grep.mean) # 46
names(grep.mean)<-grep.mean

# To remove the variables with labels containing "meanFreq"
grep.meanFreq<-grep("meanFreq", features$V2)
names(grep.meanFreq)<-grep.meanFreq
length(grep.meanFreq) # 13

grep.mean2<-grep.mean[!names(grep.mean)%in%names(grep.meanFreq)]
length(grep.mean2) # 33

grep.std<-grep("std", features$V2)
names(grep.std)<-grep.std
length(grep.std)

#### To subset data with only the mean and standard deviation of the variables for each measurement.
# To subset with mean() and std() only
grep.comb<-c(grep.mean2, grep.std)
grep.comb.ord<-order(grep.comb)
grep.comb.ord<-grep.comb[order(grep.comb)]
dim(X) # 10299, 561
X_sub<-X[, c(grep.comb.ord)] 
dim(X_sub) # 10299, 66

# subset of features$V2 which contains only the mean and standard deviation of the variables for each measurement.
features_sub<-features$V2[c(grep.comb.ord)]

# X_sub1: this is the first tidy data set according to the instruction.
dim(sub_y)
head(sub_y)
X_sub1<-cbind(sub_y, X_sub)
# save X_sub1 as an R object
save(X_sub1, file="X_sub1.RData")
# to load R object "X_sub1.RData"
load("X_sub1.RData")

# to save X_sub1 as text_delimited file
write.table(X_sub1, file="X_sub1.txt")
# to read in "X_sub1.txt"
X_sub1.rd<-read.table("X_sub1.txt", header=TRUE, sep="")


# X_sub2: the second tidy dataset according to the instruction. 
# with the average values of each variable for each subject and activity
attach(X_sub1)
X_sub2<-aggregate(X_sub1, list(By.Subject=Subject, By.Activity=Activity), mean) 
X_sub2<-X_sub2[, -c(1:2)]
save(X_sub2, file="X_sub2.RData")
write.table(X_sub2, file="X_sub2.txt")
detach(X_sub1)  
	
	
	
	






